name: Move issues to In progress status when it is linked to a branch

on:
  pull_request:
    types: [ edited, opened, reopened ]

jobs:
  issue-management:
    runs-on: ubuntu-latest
    steps:
      - name: Issue management
        uses: TorqIT/issue-management-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Project number. Can be found in the URL of your project (i.e. https://github.com/orgs/<your-org>/projects/<project-number>)
          projectNumber: 2
          # Optional comma-separated list of tester usernames
          testers: alisevych
