name: Move issues to In progress status when it is linked to a branch

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  issue-management:
    runs-on: ubuntu-latest
    steps:
      # Use this Action to generate a token using the GitHub App described above
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ISSUE_MANAGEMENT_ACTION_APP_ID }}
          private_key: ${{ secrets.ISSUE_MANAGEMENT_ACTION_PRIVATE_KEY }}

      - name: Issue management
        uses: TorqIT/issue-management-action@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          # Project number. Can be found in the URL of your project (i.e. https://github.com/orgs/<your-org>/projects/<project-number>)
          projectNumber: 2
          # Optional comma-separated list of tester usernames
          testers: alisevych
          
